const http = require('http')
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const moroRouter = require('./moro')

app.use('/api/blogs', moroRouter)
app.use(cors())
app.use(bodyParser.json())
app.listen(3001)
